export const PEER_SERVER_CONNECTED = "PEER_SERVER_CONNECTED";
export const PEER_SERVER_DISCONNECTED = "PEER_SERVER_DISCONNECTED";
export const PEER_SERVER_REGISTERED = "PEER_SERVER_REGISTERED";
export const PEER_SERVER_START_CONNECTION = "PEER_SERVER_START_CONNECTION";
export const PEER_SERVER_ERROR = "PEER_SERVER_ERROR";