export const WEBRTC_CONNECTION_STATE_CHANGE = "WEBRTC_CONNECTION_STATE_CHANGE";
export const WEBRTC_ICE_CONNECTION_STATE_CHANGE = "WEBRTC_ICE_CONNECTION_STATE_CHANGE";
export const WEBRTC_ICE_GATHERING_STATE_CHANGE = "WEBRTC_ICE_GATHERING_STATE_CHANGE";
export const WEBRTC_SIGNALING_STATE_CHANGE = "WEBRTC_SIGNALING_STATE_CHANGE";
